### ISSUE TITLE
No README or documentation

### ISSUE THREAD

**Issue by rosmcmahon** [johnletey/arGQL#2]
No README, comments, or other documentation.

Unclear how one should use this library. Also suggest more meaningful API names.

`run` - run what? Suggest something like, get first page of results? quickRun, quickQuery, getOnePage - yeah this one is hard.
`all` - all what? 
`tx` - does not seem to return a tx 😉
`fetchTxTag` - seems to get a tag value, most accurate name so far, but slight ambiguity

**Comment by johnletey** [comment]
Hiya @mcmonkeys1 👋🏻 

I have started on some documentation for the project, which you can view [here](https://github.com/johnletey/arGQL/blob/feat/docs/README.md).

Let me know what you think, and if you have any suggestions!

Definitely open to changing the function names to be less confusing 😅

**Comment by rosmcmahon** [comment]
Let's merge to master?
Could put in placeholders for the other 2 APIs, maybe

**Comment by johnletey** [comment]
@mcmonkeys1 Decided to just write the remaining documentation 😄 It's been merged to `main`.

Let me know what you think!

**Comment by rosmcmahon** [comment]
haha, I was just doing the same

**Comment by rosmcmahon** [comment]
good enough, let's close this - and maybe coordinate in future so we're not doing the same work :-D
